# Importing hyprland.conf Files

## Environments 
source=hyprland/envs.conf

## Monitors
source=hyprland/monitors.conf

## General, decoration, misc, etc..
source=hyprland/general.conf

## Windows and Layers rules
source=hyprland/rules.conf

## Animations
source=hyprland/animations.conf

## Keyboard binds
source=hyprland/binds.conf

## Executables
source=hyprland/execs.conf

# HyprMod managed settings
source = /home/cairo/.config/hypr/hyprland-gui.conf

exec-once = mpv --no-video --volume=100 /home/cairo/Desktop/Work/C/windows-11-startup-sound-effect.mp3
