# GENERAL# GENERAL
general {
  no_fade_in = true
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

background {
    path = screenshot
    blur_size = 5
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.55
    vibrancy = 0.17
    vibrancy_darkness = 0.3
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(162, 183, 203, 0.95)
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.5)
    shadow_boost = 1.2
    font_size = 150
    font_family = BigBlueTermPlus Nerd Font Mono
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
    
    animation = slideup
    animation_duration = 0.8
    animation_delay = 0
    animation_curve = decelerate
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(91, 120, 148, 0.95)
    font_size = 150
    font_family = BigBlueTermPlus Nerd Font Mono
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
    
    animation = slideup
    animation_duration = 1.0
    animation_delay = 0.1
    animation_curve = decelerate
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(133, 158, 183, 0.85)
    font_size = 14
    font_family = BigBlueTermPlus Nerd Font Mono
    position = 0, -70
    halign = center
    valign = center
    zindex = 5
    
    animation = slidedown
    animation_duration = 0.8
    animation_delay = 0.2
    animation_curve = decelerate
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 0)
    dots_size = 0.2
    dots_spacing = 1
    dots_center = true
    inner_color = rgba(33, 57, 80, 0.7)
    font_color = rgba(162, 183, 203, 0.9)
    fade_on_empty = true
    placeholder_text = <i>Use Me ;) </i>
    hide_input = false
    position = 0, -370
    halign = center
    valign = center
    zindex = 20
    
    animation = scalein
    animation_duration = 0.6
    animation_delay = 0.4
    animation_curve = decelerate
}

# USER
label {
    monitor =
    text = cmd[update:60000] $fn_greet
    color = rgba(162, 183, 203, 0.85)
    font_size = 17
    font_family = JetBrains Mono Nerd Font Mono
    position = 0, -250
    halign = center
    valign = center
    
    animation = fadeout
    animation_duration = 0.6
    animation_delay = 0.3
    animation_curve = decelerate
}
